### ISSUE TITLE
Unable to download L2B product

### ISSUE THREAD

**Issue by zxdawn** [carbon-mapper/platform-public#2]
**Describe the bug**
I have tried to download the L2 data from the s3 link provided by API:
s3://carbon-mapper-data/l2b-ch4-mfa-v1/2023/12/03/emi20231203t061106p04013/emi20231203t061106p04013_l2b-ch4-mfa-v1_cmf.tif

**To Reproduce**
```
aws s3 cp s3://carbon-mapper-data/l2b-ch4-mfa-v1/2023/12/03/emi20231203t061106p04013/emi20231203t061106p04013_l2b-ch4-mfa-v1_cmf.tif test.tif
```
I got this error:
```
fatal error: Unable to locate credentials
```

**Comment by zxdawn** [comment]
Em ... It seems I need an AWS account for downloading s3 data. Is there any free method? Thanks!

**Comment by demiurg** [comment]
Thanks for the question! There is not yet, but we are working on it. Could you give some background as to what you're trying to do with the L2B product? We might have an workaround, or alternative API for your specific use case you could use, until we do implement more public friend STAC asset links.

**Comment by zxdawn** [comment]
Thanks! I'm trying to compare our (SRON) CH4 retrieval products with CarbonMapper.

I have downloaded some plume Tiff files and found our results are similar, but the quantification differs a lot for some cases. It would be nice to have the original L2B data and check details.

**Comment by demiurg** [comment]
Have now implemented l2b asset downloading via HTTPS links that look like this:
https://api.carbonmapper.org/api/v1/catalog/asset/l2b-ch4-mfa-v1/2024/07/02/emi20240702t042921p03015/emi20240702t042921p03015_l2b-ch4-mfa-v1_cmf.tif

However, it requires you are logged and use the API token:
1. Register
2. Generate and save token on https://platform.carbonmapper.org/account/tokens/
3. Use the token via `Authorization: Bearer <token>` HTTP request header

Let me know if you run into issues.

**Comment by zxdawn** [comment]
@demiurg Thanks! It's nice to see that it's available through API. I have generated the token successfully, but am still confused about the authorization. How can I download the TIF file by adding that header to the HTTPS link?

**Comment by zxdawn** [comment]
Ha, this method works, thanks!
```
import requests

# Replace with your actual token
API_TOKEN = <my_token>
# URL of the asset you want to download
URL = 'https://api.carbonmapper.org/api/v1/catalog/asset/l2b-ch4-mfa-v1/2024/07/02/emi20240702t042921p03015/emi20240702t042921p03015_l2b-ch4-mfa-v1_cmf.tif'
# Output file path
OUTPUT_FILE = 'downloaded_file.tif'

def download_asset(url, token, output_file):
    headers = {'Authorization': f'Bearer {API_TOKEN}'}
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        with open(output_file, 'wb') as file:
            file.write(response.content)
        print(f'Successfully downloaded the file to {output_file}')
    else:
        print(f'Failed to download the file. Status code: {response.status_code}')
        print(f'Response: {response.text}')

# Call the function to download the asset
download_asset(URL, API_TOKEN, OUTPUT_FILE)
```
