### ISSUE TITLE
504 Gateway TimeOut Error

### ISSUE THREAD

**Issue by delpaul** [carbon-mapper/platform-public#7]
I have an FME workbench where using the HTTP Caller tranformer, I read data from the Carbon Mapper's API. 
Here is an example of the url: https://api.carbonmapper.org/api/v1/catalog/plumes/annotated?sort=desc&limit=1000&offset=0.
I use the same url, but I modify the offset in order to read all the data.

This did work fine until the first week of June. It is the first week of July where I noticed this issue for the first time. 

I have also tried using the csv api: https://api.carbonmapper.org/api/v1/catalog/plume-csv?sort=desc&limit=1000&offset=3001, but this does not read any data.

I think the API's are struggling to work on the Carbon Mapper webpage, because I did try similar API requests and they would throw the 504 gateway timeout error on execution.

**Comment by demiurg** [comment]
Thanks for reporting this error. The core issue is that these endpoints are computationally intensive and 1000 max row limit is too high, and should probably not be allowed, 100 would be more reasonable and reduce chance of a timeout. There is more nuance why it can be a slow endpoint, such as database statistics that determine the query plan, and the number of columns that are being joined here, but when you see a 504 error, just try to reduce your page size.

I have improved some of the database performance, and we will continue to optimize the performance.

I also see no issues with the plume-csv endpoint right now.
